In [2]:
import numpy as np

In [3]:
# スカラー
s = np.array(3)

In [6]:
## 次元数を表示
s.shape

()

In [7]:
x = s + 5

In [8]:
x

8

In [9]:
# ベクトル
v = np.array([2, 3, 4])

In [10]:
v

array([2, 3, 4])

In [11]:
## カラムが三つあって一次元であることを示す。
v.shape

(3,)

In [12]:
x = v[1]

In [13]:
x

3

In [14]:
# 一番目以降の要素を取り出す。
v[1:]

array([3, 4])

In [15]:
# 行列
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# 3x3の行列であることを示す。
m.shape

(3, 3)

In [18]:
m[1]

array([4, 5, 6])

In [20]:
m[1][1]

5