In [3]:
import numpy as np
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib.pyplot as plt

In [15]:
# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [16]:
# シグモイド関数の導関数（シグモイド関数を微分した関数）
def sigmoid_der(x):
    return (1 - sigmoid(x)) * sigmoid(x)

In [17]:
# 学習率(learning rate)
Ir = 0.5
x = np.array([2, 3, 4, 5])

In [18]:
y = np.array(0.4)

# 重みの初期値
w = np.array([0.4, -0.4, 0.3, 0.2])

In [19]:
# ドット積
h = np.dot(x, w)

In [20]:
# もっとも正解に近い関数（ワイハっト）
y_hat = sigmoid(h)

In [21]:
# 誤差関数
error = y - y_hat

In [22]:
# 誤差項
error_term = error * sigmoid_der(h)

In [24]:
# xはnumpyで行列にしているが、numpyの行列は自動的にそれぞれの要素に掛け合わせてくれる
del_w = Ir * error_term * x

In [25]:
del_w

array([-0.05577017, -0.08365525, -0.11154034, -0.13942542])

In [26]:
print('output: ')
print(h)

output: 
1.8


In [27]:
print('error: ')
print(error)

error
-0.45814893509951227


In [28]:
print('del_w: ')
print(del_w)

del_w: 
[-0.05577017 -0.08365525 -0.11154034 -0.13942542]


In [29]:
w

array([ 0.4, -0.4,  0.3,  0.2])

In [30]:
w + del_w

array([ 0.34422983, -0.48365525,  0.18845966,  0.06057458])

In [31]:
# 多層ニューラルネットの練習
# 入力層は4つのノードを持つ
# 隠れそうは3つのノード
# 出力層は2つのノード
# 活性化関数にはシグモイド関数を使用

In [32]:
num_input = 4
num_hidden = 3
num_output = 2

In [34]:
# 指定した数の乱数を表示
np.random.seed(45)
x = np.random.randn(4)

In [35]:
x

array([ 0.02637477,  0.2603217 , -0.39514554, -0.20430091])

In [36]:
# 入力層から隠れそうへの重みの初期化
## np.random.normalは正規分布に従った値を生成
## scaleは分散
w_in_h = np.random.normal(0, scale=0.1, size=(num_input, num_hidden))

In [37]:
w_in_h

array([[-0.12716327, -0.25968786,  0.02896809],
       [-0.08733046,  0.03940727,  0.09351055],
       [-0.00156847,  0.0259596 , -0.14733142],
       [ 0.08019266, -0.17507524, -0.04950519]])

In [38]:
# 隠れそうから出力層への重みの初期化
w_h_out =  np.random.normal(0, scale=0.1, size=(num_hidden, num_output))

In [39]:
w_h_out

array([[-0.10086008,  0.00252442],
       [-0.01215069, -0.15468732],
       [-0.0606944 , -0.13938127]])

In [43]:
# 隠れそうの入力値と出力値
h_in = np.dot(x, w_in_h)
h_out = sigmoid(h_in)

In [44]:
print(h_out)

[0.48953863 0.50722939 0.52334256]


In [46]:
# 出力層の入力値と出力値
out_in =np.dot(h_out, w_h_out)
out_out = sigmoid(out_in)

In [47]:
print(out_out)

[0.47818834 0.46252782]
